### ISSUE TITLE
UNKNOWN_ERROR on send every time.

### ISSUE THREAD

**Issue by Random-Stack-Random-Day** [deanpcmad/omniauth-discord#12]
Just genuinely curious if this lib works anymore - I am noticing that Implicit Workflow works perfectly, but if I use this omniauth method I instantly get 'UNKNOWN_ERROR' on Discords side. However the console never gets a response, just initiates it. Is this gem still presently working?

**Comment by Random-Stack-Random-Day** [comment]
Closing this issue as it was an issue on Discord's side. Checking XHR made it obvious of the issue. For future notice: Deleting and re-adding your RedirectUI resolved it.

**Comment by doutatsu** [comment]
@dnorthrupva What did you mean by `Deleting and re-adding your RedirectUI resolved it.`?
From I can see I am getting an error because the gem takes `localhost` instead of `127.0.0.1`, but trying to overwrite it in the initializer with `callback_path`, but it just gets added on top of the gem redirect url
